class_name ArenaMap
extends Node2D
## An arena's ground, decoration and surrounding tree line.
##
## Generated by tools/build_arena_map.gd: change the tool and re-run it rather
## than editing the scene. This node only owns the map's extents. Whoever
## instances it frames the camera on map_rect and keeps play inside
## playable_rect, which the Bounds walls already enforce for bodies.
##
## Trees are y-sorted against this node's siblings, so a hero passes behind
## the trees below them only when this node's parent is y-sorted too.

## Where bodies can stand, in this node's space.
@export var playable_rect: Rect2 = Rect2()
## Everything drawn, tree line included, in this node's space.
@export var map_rect: Rect2 = Rect2()


func _ready() -> void:
	if not map_rect.has_area() or not map_rect.encloses(playable_rect):
		push_error("ArenaMap: map_rect and playable_rect are unset; re-run the generator.")
